services:

  vllm:
    image: vllm/vllm-openai:v0.7.3
    command:
      - --served-model-name
      - default-model
      - --model
      - Qwen/Qwen2.5-7B-Instruct
    restart: unless-stopped
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
       HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8000:8000"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

  vllm-embeddings:
    image: vllm/vllm-openai:v0.8.5.post1
    command:
      - --served-model-name
      - default-model
      - --model
      - BAAI/bge-m3
    restart: unless-stopped
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
       HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8100:8000"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['1']
                capabilities: [gpu]