services:

  api:
    image: registry.cloud.neoali.com/datastreams/ex-gpt/ai-api:0.1.7
    ports:
      - "8080:80"
    depends_on:
      - qdrant
    environment:
      - CHAT_MODEL_ENDPOINT=${CHAT_MODEL_ENDPOINT}
      - CHAT_MODEL_NAME=default-model
      - EMBEDDING_MODEL_ENDPOINT=${EMBEDDING_MODEL_ENDPOINT}
      - EMBEDDING_MODEL_NAME=default-model
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=default
      - MODEL_SERVER_API_KEY=${MODEL_SERVER_API_KEY}
    restart: unless-stopped

  qdrant:
    image: registry.cloud.neoali.com/datastreams/ex-gpt/qdrant:demo-v3
    ports:
      - "6333:6333"
    restart: unless-stopped

  minio:
    image: registry.cloud.neoali.com/datastreams/ex-gpt/minio:v1
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9090:9090"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: neoali
      MINIO_ROOT_PASSWORD: exgpt2025
    # volumes:
      # - ./data:/data
    command: server /data --console-address ":9090"