version: '3.8'

services:
  ragflow:
    image: infiniflow/ragflow:v0.19.1
    container_name: ex-gpt-ragflow
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_PASSWORD=ragflow123
      - MYSQL_ROOT_PASSWORD=ragflow123
      - MINIO_ROOT_USER=ragflow
      - MINIO_ROOT_PASSWORD=ragflow123
      - SVR_HTTP_PORT=80
      # LLM API 키 설정 (환경변수에서 가져옴)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://localhost:11434}
    volumes:
      - ragflow_data:/ragflow/data
      - ragflow_models:/root/.ragflow
      # RAGFlow 설정 파일을 위한 볼륨 (선택사항)
      - ./ragflow_config:/ragflow/conf/docker
    depends_on:
      - ragflow-mysql
      - ragflow-redis
      - ragflow-minio
      - ragflow-elasticsearch
    networks:
      - ragflow-network

  ragflow-mysql:
    image: mysql:8.0
    container_name: ex-gpt-ragflow-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ragflow123
      - MYSQL_DATABASE=ragflow
      - MYSQL_USER=ragflow
      - MYSQL_PASSWORD=ragflow123
    volumes:
      - ragflow_mysql_data:/var/lib/mysql
    networks:
      - ragflow-network

  ragflow-redis:
    image: redis:7.2
    container_name: ex-gpt-ragflow-redis
    restart: always
    command: redis-server --requirepass ragflow123
    volumes:
      - ragflow_redis_data:/data
    networks:
      - ragflow-network

  ragflow-minio:
    image: minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: ex-gpt-ragflow-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=ragflow
      - MINIO_ROOT_PASSWORD=ragflow123
    ports:
      - "9001:9001"
    volumes:
      - ragflow_minio_data:/data
    networks:
      - ragflow-network

  ragflow-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ex-gpt-ragflow-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ragflow_es_data:/usr/share/elasticsearch/data
    networks:
      - ragflow-network

volumes:
  ragflow_data:
  ragflow_models:
  ragflow_mysql_data:
  ragflow_redis_data:
  ragflow_minio_data:
  ragflow_es_data:

networks:
  ragflow-network:
    driver: bridge
