services:

  qdrant:
    image: registry.cloud.neoali.com/datastreams/ex-gpt/qdrant:demo-v3
    ports:
      - "6333:6333"
    restart: unless-stopped

  vllm-embeddings:
    image: vllm/vllm-openai:v0.8.5.post1
    command:
      - --served-model-name
      - default-model
      - --model
      - Qwen/Qwen3-Embedding-0.6B
    restart: unless-stopped
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
       HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8100:8000"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]