[tool.poetry]
name = "ex-gpt-demo"
version = "0.1.0"
description = ""
authors = ["back2zion <back2zion@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.3"
flask = "^3.1.1"
flask-cors = "^6.0.0"
requests = "^2.32.3"
python-docx = "^1.1.2"
pymupdf = "^1.26.0"
olefile = "^0.47"
transformers = "^4.44.0"
tokenizers = "^0.19.1"
torch = {version = "^2.4.0+cu121", source = "pytorch"}
torchvision = {version = "^0.19.0+cu121", source = "pytorch"}
torchaudio = {version = "^2.4.0+cu121", source = "pytorch"}
pillow = "^11.2.1"
einops = "^0.8.1"
timm = "^1.0.15"
openai-whisper = "^20231117"
accelerate = "^1.2.0"
noisereduce = "^3.0.0"
pydub = "^0.25.1"
librosa = "^0.11.0"
pytesseract = "^0.3.13"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
package-mode = false